config/routes.rb
Rails.application.routes.draw do
  
  devise_for :usuarios
  resources :tareas do
    resources :comentarios
  end
  #get 'tareas', to: 'tareas#index'
  #get 'tareas/new', to:'tareas#new'
  #post 'tareas', to: 'tareas#create'
  #get 'tareas/:id', to: 'tareas#show'
 # delete 'tareas/:id', to: 'tareas#destroy'
  #get 'tareas/:id/edit', to: 'tareas#edit'
 # put 'tareas/:id',  to: 'tareas#update'
  
  get 'bienvenido/index'
  root 'bienvenido#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
	validates :contenido, presence: true
  belongs_to :usuario
  belongs_to :tarea
end

app/models/tarea.rb
class Tarea < ApplicationRecord
	validates :titulo,presence: true
	validates :descripcion, presence: true
	belongs_to :usuario
	has_many :comentarios

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tareas
         has_many :comentarios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  	#carga la vista index
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action  :authenticate_usuario!, except:[:index, :show]
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]
  before_action :set_tarea

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)
    @comentario.usuario = current_usuario
    @comentario.tarea =@tarea

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario.tarea, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def set_tarea
      @tarea =Tarea.find (params[:tarea_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:usuario_id, :tarea_id, :contenido)
    end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController

before_action :authenticate_usuario!, except:[:index, :show]
before_action :set_tarea, except:[:index, :new, :create]

  def index
  	@tareas = Tarea.all
  	#select * from tareas
  end

  def new
  	@tarea= Tarea.new

  end
   def create
  	@tarea = Tarea.new(tarea_params)
    @tarea.usuario = current_usuario
  	
  	if @tarea.save 
  	#este metodo hace el insert into(tareas y descripcion) values (formulario)
  	redirect_to @tarea #action show  cambio controller:'tareas', action:'show',id:@tarea.id
  	else

  		render :new
    end
end
  	def show
      @comentario = Comentario.new
  		#@tarea =Tarea.find(params[:id])
  		#selectfrom tareas where id=
    
  	end
    def destroy
     #@tarea =Tarea.find(params[:id])
     @tarea.destroy
     redirect_to tareas_path # cambio controller:"tareas", action:"index"
     #para eliminar tareas 
    end

    def edit
     #@tarea =Tarea.find(params[:id])
      end

     def update
     #@tarea= Tarea.find (params[:id])
     if @tarea.update(tarea_params) 
     redirect_to @tarea # cambio =>controller:"tareas", action:"show", id: @tarea.id

     else
    render :edit
    end
  end

private #metodos que solo funcionan dentro de esta clase
  def set_tarea
      @tarea= Tarea.find (params[:id])
   end

def tarea_params
   params.require(:tarea).permit(:titulo, :descripcion)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/bienvenido/index.html.erb
<% if usuario_signed_in? %>
<h1> Bienvenido <%=current_usuario.email %></h1>

<%else%>
<h1>Bienvenidos a mi sitio</h1>

<%end%>

<p>Mi primer sitio en Rails</p>



<!--<% frutas = ['manzana','pera','mango']%>
<ul>
<%frutas.each do |fruta| %>
	<li> <%=fruta %>  </li>

	<% end %>
</ul>-->

app/views/comentarios/_form.html.erb
<%= form_for([@tarea, @comentario]) do |form| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="form-group">
    <%= form.label :contenido %>
    <%= form.text_area :contenido, id: :comentario_contenido, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Comentar" , class: "btn btn-info"%>
  </div>
 <%end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Tarea</th>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.usuario %></td>
        <td><%= comentario.tarea %></td>
        <td><%= comentario.contenido %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <strong>Tarea:</strong>
  <%= @comentario.tarea %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @comentario.contenido %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sitio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  		<ul class= "navbar-nav">
  			<li class="nav-item">
  				<%= link_to "Inicio", bienvenido_index_path, class:"nav-link" %>					
  			</li>
    <li class=" nav-item">
    	<%= link_to "Tareas", tareas_path, class:"nav-link" %>

  <li class= "nav-item">
   <%= link_to "Crear tarea", new_tarea_path, class:"nav-link"%>
 	
 </li>

    </li>
    <% if usuario_signed_in? %>
        <li class= "nav-item">
      <%= link_to "Cerrar Sesion", destroy_usuario_session_path, method:"delete" ,class: "nav-link"%>
    </li>
    <%else%>
    <li class= "nav-item">
      <%= link_to "Iniciar Sesion", new_usuario_session_path, class: "nav-link"%>
    </li>

     <li class= "nav-item">
      <%= link_to "Crear cuenta", new_usuario_registration_path, class: "nav-link"%>
    </li>
   <%end%>
  		</ul>

  	</nav>
    <p><%= alert %></p>
    <p><%=  notice %></p>
    <%= yield %>
</div>
  </body>
</html>

app/views/tareas/_formulario.html.erb
<% @tarea.errors.full_messages.each do |mensaje|%>
<p class="alert alert-danger"><%=mensaje%></p>
<% end %>

<%=form_for(@tarea) do |f|%>
	<div class ="form-group">
		<label>Titulo</label>
		<%= f.text_field :titulo, class: "form-control", :requiered =>true%>

		<!--<input type="text" name="titulo" class="form-control">-->

	</div>

<div class= "form-group">
	<label>Descripción</label>
	<%= f.text_area :descripcion, class: "form-control", :required =>true%>

</div>
<%= f.submit boton, class:"btn btn-" +color_boton%>

<% end %>

app/views/tareas/create.html.erb
<p>tarea creada</p>

app/views/tareas/edit.html.erb
<h1>Editar tarea</h1>
<%= render "formulario", boton:"Editar",color_boton:"warning" %>

app/views/tareas/index.html.erb
<h1>Mis Tareas</h1>
<table class="table">
	<thead class="thead-dark">
	<th>Tarea</th>
	<th>Editar</th>
	<th>Eliminar</th>
</thead>

	<% @tareas.each do |tarea|%>


<tr>
  <td><%= link_to tarea.titulo, tarea %></td>
  <td><%= link_to "Editar", edit_tarea_path(tarea) ,class:"btn btn-warning"%>
   <td><%= link_to "Eliminar",tarea, method: "delete", data: { confirm: "¿Estás seguro?"}, class:"btn btn-danger"%></td>
</tr>
	<% end %>
	
</table>

app/views/tareas/new.html.erb
<h1>Tarea Nueva</h1>
<%= render "formulario", boton:"Crear", color_boton:"primary"%>
	

app/views/tareas/show.html.erb
<div class="card">
	<div class="card-body">
		<div class = "card-title"></div>
		<h2><%= @tarea.titulo %><h2>

     </div>

 <div class="card-text">
      <p><%= @tarea.descripcion%></p>

     </div>
  </div>

<% unless @tarea.usuario.nil?%>
	

<p>Escrito por: <%=@tarea.usuario.email %></p>
<% end %>
<h3>Agregar comentario</h3>
<%= render "comentarios/form"%>
<h3>Comentarios</h3>
<ul>
	<% @tarea.comentarios.each do |comentario| %>
	<li> <%= comentario.contenido %></li>
	<%end%>
</ul>